source 'https://rubygems.org'
gem 'capistrano', '~> 3.7.1'
gem 'capistrano-symfony', '~> 0.4.0'
gem 'capistrano-bower', '~> 1.1.0'
gem 'capistrano-composer', '~> 0.0.6'
gem 'capistrano-file-permissions', '~> 0.1.1'
gem 'capistrano-gulp', '~> 0.0.1'
gem 'capistrano-maintenance', '~> 0.0.3'
gem 'capistrano-npm', '~> 1.0.1'
gem 'capistrano-touch-linked-files', '~> 0.3.0'
