# app/config/security.yml

security:
    encoders:
       Symfony\Component\Security\Core\User\User: plaintext
           # algorithm: bcrypt
            #cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
               users:

    firewalls:
             dev:
                 pattern:  ^/(_(profiler|wdt)|css|images|js)/
                 security: false

             main:
                 pattern:   ^/
                 anonymous: true
                 provider:  in_memory
                 form_login:
                    login_path: login
                    check_path: login_check
                 logout:
                    path:   logout
                    target: /platform

        #default:
            # anonymous: ~
             # activate different ways to authenticate

             # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
             #http_basic: ~

              # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
              #form_login: ~

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

        #- { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/user, roles: ROLE_USER }

